### ISSUE TITLE
Cross-Site Scripting / Cross-Site Request Forgery

### ISSUE THREAD

**Issue by natiq2004** [revive-adserver/revive-adserver#1023]
https://www.exploit-db.com/exploits/41939

https://www.youtube.com/watch?v=wFuN-ADlJpM

**Comment by erikgeurts** [comment]
Why are you reporting issues from as far back as April 2017 in an ancient version of the software?

If you've got a new discovery, please disclose responsibly by following the directions at https://hackerone.com/revive_adserver

**Comment by mbeccati** [comment]
Yes, it's old news. Besides, it's vital for the proper functioning of Revive Adserver to allow any <script> into HTML banners and/or prepend/append codes.

**Comment by andrewatfornax** [comment]
Thank you for security related bug report for Revive Adserver.

We would kindly request that all security reports are not posted in GitHub, and instead, are raised via our HackerOne page, so that we can investigate them privately, without exposing a potential issue more widely. 

This gives us a chance to patch the issue (if verified) before public disclosure.

As a result, we are deleting this issue from GitHub. If you could please re-post the issue via HackerOne, that would be greatly appreciated. 

Sincerely,

The Revive Adserver team
