### ISSUE TITLE
interstitial banner not showing in WordPress site

### ISSUE THREAD

**Issue by mbadaone** [revive-adserver/revive-adserver#1032]
Problem: Interstitial banner not showing on a WordPress site. Giving the following error 

(index):1550 A parser-blocking, cross site (i.e. different eTLD+1) script, https://servedby.revive-adserver.net/al.php?zoneid=395&target=_blank&ct0={clickurl_enc}&layerstyle=simple&align=left&valign=bottom&padding=2&closetime=60&padding=2&shifth=0&shiftv=0&closebutton=t&nobg=t&noborder=t, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.

Steps To Reproduce:
Used a plugin called Add to all to alter header to include the invocation code and its not showing

**Comment by erikgeurts** [comment]
Thanks for reporting this. My personal take on this is that the internet moved away from using interstitials a long time ago. As such, I think we may not give the highest priority to this.

**Comment by mbeccati** [comment]
I'd tend to agree. Interstitials had been developed when HTML4 was shiny new and DHTML was the new trend. I sometimes wonder how they can be still working. Unfortunately my frontend skills are not up to par with todays technologies, so we'll need external help to either revamp them or finally deprecate them.

**Comment by andrewatfornax** [comment]
I totally agree with you both @erikgeurts and @mbeccati - it feels like we're at the point where Interstitials should be deprecated in Revive Adserver.

@mbadaone - I'd be very interested in your feedback on why you're using Interstitials instead of the more modern JS or Async invocation tags. Is there a particular reason for using Interstitials? Is there a reason for you why they are better than JS or Async?

Feedback wold be very welcome!

**Comment by mbadaone** [comment]
I think interstitials are still very much relevant because of high visibility and positioning flexibility. I found a solution to circumvent it for now by adding **async** on the opening script tag.

**Comment by allshowbiz** [comment]
@mbadaone how did you do it im getting the same 403 Error from this i cant fix it feeling a bit lost as to what to do the asynchronous version warps and distorts the Wordpress page using Elementor or does not show at all the JS version throws the 403 because the document.write i found this https://developers.google.com/web/updates/2016/08/removing-document-write from inspecting the error please help what can i do maybe the new version has different options

**Comment by erikgeurts** [comment]
Given that we haven't had much feedback from the community about the desirability of continued support for this, this issue can now be closed.
