### ISSUE TITLE
Display "Last Login Date" in user list

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#1051]
In the list of users of any agency (or in the list of sysadmins), there is a column that shows the "Date linked". This is essentially the date the username was created and/or linked to the account.

There is a column in the rv_users table for "data_last_login", which is null if the user hasn't ever logged in, or it contains the timestamp of their last login.

My proposal is to display this date of last login in the list of users of an account (showing "never" in case the timestamp is null). This will help administrators, or other users who manage user access to an account, for example by identifyings who haven't logged in for a very long time, or who never logged in at all.

**Comment by andrewatfornax** [comment]
Hi @erikgeurts,

I've had a look into this one, and it's actually a really, really simple UI change, because the template actually already has everything we need for this - it's just a matter of adjusting an "if" condition, and the data is there.

The difficulty is that the last logged in date is in UTC, which is the format we should be using for all date/time data in the database - but looks like the date/time for the creation of the user is in the local time of the creating user.

Code for this is in lib/max/Dal/DataObjects/Users.php.

@mbeccati, just wondering what your thoughts are on this please. I am thinking that possibly the correct approach is to convert this database field into UTC on next upgrade - but then, we don't know for sure what timezone the data was in when it was created (users may have updated their timezone to correct a setup problem after creating some users).

Maybe the best approach is just to convert the last login date to the viewing users' timezone, and leave the date created field alone?

**Comment by erikgeurts** [comment]
You're writing about the date the user was created, which is what's currently displayed already, whereas I was hoping we could remove that and replace it with the user's last login date. I agree it's a bit odd that the date stamp of the user creation event is stored in local time, but that doesn't matter all that much.

I just checked and when I log in, the value in the date_last_login column is updated, and it is in UTC.

**Comment by mbeccati** [comment]
Maybe we can fix saving such dates and avoid the migration. If we only display the date/time of last login, hopefully the list will be correct at some point.
