### ISSUE TITLE
open redirect (oadest url) ck.php revive 4.2.1

### ISSUE THREAD

**Issue by becksgrohl** [revive-adserver/revive-adserver#1068]
dear all, 

we've found bug in our revive about ck.php (oadest)

https://revive.com/www/delivery/ck.php?oadest=https://evil.com -> it will be redirect to url destination

we read this url https://packetstormsecurity.com/files/152671/REVIVE-SA-2019-001.txt 
that we should upgrade version, but this bug (as we think is a bug) still can open redirect 

this is issue will harm our site and the victims could be redirect to phissing website 

could you guide us what we should do again, even after upgrade version 4.2.1 still can open redirect

**Comment by erikgeurts** [comment]
Thanks for your report. The behavior you noticed is there by design. I'll explain below.

One of the core requirements of an adserver is to not only redirect users to the destination when they click on a banner, but to also track that the click has happened. To do this successfully, click actions on banners need to firstly come to Revive Adserver, to record the click, and then redirect the user.

One solution to ensure that arbitrary URL redirection behavior ("Open Redirects") is prevented would be to record the destination URL for each banner in the database, and to then redirect based on the banner that was clicked.

However, this would require that Revive Adserver knows the destination URL for every banner, which would then mean that external banners from other networks could not be used.

As a result, we typically do not treat Open Redirects as a security vulnerability, as most users of the software actually require the ability to redirect to supplied, non-verified URLs from the software. Changing the software to prevent Open Redirects would effectively prevent users from doing what they actually want the software to do.

**Comment by becksgrohl** [comment]
> Thanks for your report. The behavior you noticed is there by design. I'll explain below.
> 
> One of the core requirements of an adserver is to not only redirect users to the destination when they click on a banner, but to also track that the click has happened. To do this successfully, click actions on banners need to firstly come to Revive Adserver, to record the click, and then redirect the user.
> 
> One solution to ensure that arbitrary URL redirection behavior ("Open Redirects") is prevented would be to record the destination URL for each banner in the database, and to then redirect based on the banner that was clicked.
> 
> However, this would require that Revive Adserver knows the destination URL for every banner, which would then mean that external banners from other networks could not be used.
> 
> As a result, we typically do not treat Open Redirects as a security vulnerability, as most users of the software actually require the ability to redirect to supplied, non-verified URLs from the software. Changing the software to prevent Open Redirects would effectively prevent users from doing what they actually want the software to do.


dear Mr Erik, 

thanks for your suggestions, advices, and many comments above

now, we will coordinate with the team about this .. and i'll give your suggest above that open redirect not treat as security vulnerability

**Comment by erikgeurts** [comment]
For actual vulnerability reports, we strongly recommend you first study https://www.revive-adserver.com/security/ and then use https://hackerone.com/revive_adserver to report them. Posting a vulnerability publicly on Github is **never** a good idea, for any project.

**Comment by mbeccati** [comment]
We've revisited our decision and this will be fixed in the next release.
