### ISSUE TITLE
Async invocation code not following delivery rules

### ISSUE THREAD

**Issue by delatush** [revive-adserver/revive-adserver#1100]
I have multiple ads running per page, anywhere's from 3-15 ads of different types on one page. Each of these ads have banner delivery rules deployed on the invocation code (set on the banner themselves too).

example of ads run:

> 						  
> 
>   `<`ins data-revive-zoneid="40" data-revive-paysite="230" data-revive-target="_blank" data-revive-id="488427b269b96ef4762c3e8ff1bd9555"></ins>
> <script async src="//MYSERVER.com/www/delivery/asyncjs.php"></script>
> 
> 
> 						  
>`<` ins data-revive-zoneid="41" data-revive-paysite="100" data-revive-target="_blank" data-revive-id="488427b269b96ef4762c3e8ff1bd9555"></ins>
> <script async src="//MYSERVER.com/www/delivery/asyncjs.php"></script>
> 
> 
> 						  
> `<`ins data-revive-zoneid="42" data-revive-paysite="220" data-revive-target="_blank" data-revive-id="488427b269b96ef4762c3e8ff1bd9555"></ins>
> <script async src="//MYSERVER.com/www/delivery/asyncjs.php"></script>
> 
> 

When my page loads and the ads are retrieved - they all come from the same campaign regardless of my rules passed in. Inspecting and following the code calls, I can see how all the zones are passed in pipe delimited BUT it only passes in the rule that is set on the very last ad thus resulting (in my case) all of my ads showing from the same campaign. 

Example of the call:

VM13246:1 XHR finished loading: GET "https://MYSERVER.com/www/delivery/asyncspc.php?zones=40%7C41%7C42&prefix=revive-0-&target=_blank&paysite=220&block=1&loc=https%3A%2F%MYDOMAIN.com%2F

This BUG only happens w/ async invocation and not javascript writes. But the javascript invocation is super taxing on speed when calling 15 banners per page.

**Comment by fishsaidno** [comment]
I've just stumbled upon this bug too.
Perhaps not a bug - but certainly not what you'd expect from reading the docs.
As this behaviour is specific to async invocation tags, it's confusing when migrating from other tag types.

Perhaps the documentation [here](https://documentation.revive-adserver.com/display/DOCS/Tag+Variables) needs another note added for `Asynchronous JS`, referencing this issue.

Resolution would involve:
1. Adjusting `www/delivery/async.js` such that when it gets the attributes (tag variables) from each `<ins>` element, instead of adding the key/value directly to the data object (resulting in duplicate keys being overwritten by the last tag on the page). It collects them as an array & passes to `asyncspc.php` as a `|` delimited string - just as it does with `zones`.
2. Adjusting `www/delivery/asyncspc.php` to handle this pipe delimited string and swap out values as needed when it loops through the zones and selects the ad for each zone.

`1` Was simple enough to sort out. `2` Not so much, haha. 🤨 

It's worth noting that this issue applies to the `source`, `block`, `blockcampaign` options as well.
e.g. If the last async tag on the page has `data-revive-block="1"` then Revive considers all async tags on the page to have this option enabled.

**Comment by mbeccati** [comment]
By design, single page call invoication types, like async is, only allow one set of parameters. Typically the last one "wins" and is what will be sent to Revive Adserver.

**Comment by fishsaidno** [comment]
Unfortunate functionality wise, but understandable. Thanks for the clarification.
