### ISSUE TITLE
Upgrade wizard issue while recompiling ACLS

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#1103]
While performing upgrades to v5.0.0 for installations with large sets of banners and their corresponding ACLS rows, the upgrade wizard can time out, and/or run out of memory, during the final step of recompiling the delivery rules and delivery rule sets.

In itself, this does not have to be catastrophic, since there is a tool in the UI to run the check and recompile process manually afterwards. However, this will likely also run out of memory and/or time out.

An improvement in speed or reduction in memory usage might be helpful.

**Comment by erikgeurts** [comment]
As a follow up: while upgrading an installation with a relatively small number of banners (slightly more than 800) I encountered an issue with the delivery rule sets. There were about 30 of them. During the upgrade, the process encountered a timeout, and I was also not able to get the manual recompile to complete. I ended up manually saving and thus recompiling all delivery rule sets, which appears to have been successful.

**Comment by tvvpm** [comment]
I found myself in the same situation. Perhaps could help that when doing a "check of delivery rules", in the result listing, you can get which are the banners in active campaigns, because I have more than a thousand delivery rules. Actually I have 1110 rules still pending of compile, all of them beloging to past campaigns.

I have gone through every active campaign checking every banner.

**Comment by erikgeurts** [comment]
There is a tool in the UI to check and if needed to recompile all delivery rules. So in most cases, there is no need to go through the banners manually.
