### ISSUE TITLE
Google Analytics tracking inaccurate?

### ISSUE THREAD

**Issue by 420Banners** [revive-adserver/revive-adserver#1199]
We use Revive Adserver to set up banner ads.

There is a campaign with an affiliate link (not a redirect, just a long url) that's been set up for the advertiser to use Google Analytics to track stats they receive from our website using Revive Adserver. We've received a report that Revive Adserver clicks do not match with what Google Analytics reports. 

What could be the issue here and how do we resolve it?

**Comment by erikgeurts** [comment]
Discrepancies between measuring systems are a common scenario, and do not hint to a bug.

We prefer to use the Github Issues area for actual bugs only. We recommend you post this question on our community forums at https://forum.revive-adserver.com so that members of the community can respond. If you've already posted it there, please be patient. It can take a few days to a few weeks before you get a response.
