### ISSUE TITLE
Updating Revive Adserver - Database strange behavior

### ISSUE THREAD

**Issue by SmartandCom** [revive-adserver/revive-adserver#1219]
Hi,

I duplicated the database before the upgrade. Everything went fine, but by simply copying the database, it's getting bigger every time. As an example, our database was 640 MB before copy, the copy version with exactly the same data is now 1.55 GB.

2 tables seems to be mainly affected, see below :

Before :

 rv_data_summary_ad_hourly - 814 639 entries - 128.3 MB

rv_data_summary_ad_zone_assoc - 1 604 550 entries - 342.6 MB

After :

 rv_data_summary_ad_hourly - 2 307 907 entries - 366.5 MB

rv_data_summary_ad_zone_assoc - 3 568 792 entries - 804 MB

 

It occurs during every update, over time it will go to disaster

any idea why this happens and how to clean those tables growing by magic ?

**Comment by erikgeurts** [comment]
This is indeed peculiar behavior, but it's not something we've ever observed or heard of. It is not likely to be a bug. If this was a common thing, I would have seen it before (I've done thousands of updates in my run with Revive Adserver and its predecessors).

Please consider posting your question on our community forums at https://forum.revive-adserver.com so that someone from the community might be able to help you. If you've already done so, then please be patient for a response to occur.

If this turns out to be some kind of bug after all, we'll be glad to re-open this issue.
