### ISSUE TITLE
Installation failed to create the core tables

### ISSUE THREAD

**Issue by mohamedhasan2002** [revive-adserver/revive-adserver#1246]
It says 'Installation failed to create the core tables' first then later it says 'The database you have chosen already contains tables with the prefix rv_
Please either remove these tables or choose a new prefix'
![Screenshot from 2021-02-19 15-57-12](https://user-images.githubusercontent.com/28563234/108495735-276a3280-72cf-11eb-9deb-4bbba9b85799.png)

**Comment by erikgeurts** [comment]
We do not encourage the use of Github issues for support questions.

Please consider posting your question on the community forums at https://forum.revive-adserver.com. If you've already done this, then it may take some time before another community member responds.

If this turns out to be a bug after all, we'll be more than happy to re-open this issue.
