### ISSUE TITLE
Revive Adserver counts the views for statistics of the JS code while banners in the zone are hidden?

### ISSUE THREAD

**Issue by fritexvz** [revive-adserver/revive-adserver#1255]
From the title of this issue, I have an issue where the JavaScript code for the zone is placed at the Website for any case of further banners to show up due to clients needs.

But, as the JS code is placed at the right position on the Website and there are either no banners added to the zone, or if any, they are hidden from showing up, but in the statistics the Revive Adserver still counts the views of actually "nothing"?

Why is that and how is this possible?

Thank you

**Comment by erikgeurts** [comment]
In Revive Adserver we call these 'impressions' not views. The impressions are counted using a measurement pixel that's delivered to the browser. This measurement pixel is triggered regardless of the viewability of the zone. So even if you position the zone outside of the visible area of a site, an impression is still counted. If there are no banners linked to the zone, it counts a blank impression. This is not a bug, it is intentional.

**Comment by erikgeurts** [comment]
In addition, we do not offer dedicated support with the software. You can consider posting your question at https://forum.revive-adserver.com/ .
(Do not reply - this message was sent from an unmonitored email address)
