### ISSUE TITLE
Modern and safer password storage

### ISSUE THREAD

**Issue by mbeccati** [revive-adserver/revive-adserver#1291]
Revive still stores md5 password hashes, which can lead to security risks if the data is somehow leaked or accessed by unauthorised people.

A modern substitute needs to idendified and implemented with a proper upgrade path, if possible, e.g.
1. During the upgrade the admin password can be checked using the md5 hash
2. All stored md5 hashes are invalidated
3. The admin password is safely re-hashed and saved
4. All other users have to go through password recovery to set a new password

If at all possible, some indication should be given during login for users who haven't reset the password, or password recovery initiated for all active users during upgrade.

**Comment by mbeccati** [comment]
I think I've made a good progess with steps 1-3.

I'm still uncertain on what to to with the other users on the system as I don't think there's a good solution that works for everybody. A few random bits:

* Allow first md5 password check and upgrade the hash upon login. Pros: painless - Cons: bad security!
* Same as above for a certain period of time. Pros: slightly improved - Cons: still bad security! - Open: how to communicate that
* Disallow md5. Rely on password recovery alone. Pros: no code needed - Cons: meh user experience - Open: how to communicate that

**Comment by twmobius** [comment]
I am not entirely sure if this is correct, but one could do the something like the following in the `authentication.php`:

```
function checkPassword($username, $password)
{
  [...]

  $doUser = OA_Dal::factoryDO('users');
  $doUser->username = $username ?: ''; // I think this will not work the way I am describing, when can username be empty?
  
  $doUser->find();
  
  if ($doUser->fetch()) {
    if( strlen($doUser->password) == 32 && $doUser->password == md5($password) ) {
      $newHashedPassword = password_hash($password, PASSWORD_DEFAULT);
      $doUser->password = $newHashedPassword;
  
      $doUser->update();
      $oLock->release();  
  
      return $doUser;
    } else {
      if( password_verify($doUser->password, $password) ) {
        $oLock->release();  
  
        return $doUser;
      }
    }
  }

  [...]
}
```

**Comment by mbeccati** [comment]
Thanks @twmobius!

Please see c51a38f502c802ee4dcb3da6e5ea834c5fe05e3f, it is fairly similar to what you've come up with, but allows md5 authentication only during the upgrade to 5.4 or later.

We surely could allow authentication against the md5 hash stored on the database, but tbh that makes me nervous and basically defeats the purpose of the improvement when there are old/unused/inactive/hacked users on the system.

**Comment by twmobius** [comment]
I get it. My only consideration is that you are adding function parameters (`$useMd5`) which are by definition transitional, are not used in the main application and we'll be removed in future versions. Where as with a transition `if block` like the one I mentioned, the whole process is transparent to anyone using the code, and can be removed without function signature changes.

Either way you decide to proceed I would think of it as publishing a minor version which deprecates the md5 encryption and provides some sort of upgrade path, and the next minor version removes the md5 encryption entirely and forces the users to reset their passwords to log in. No extra steps are required for this step, since by just removing the "migration code" and leave the rest of the application as it, the md5 hash will never much the `password_verify()` and the users will be forced to follow the reset password path.

Also at last, I'd suggest making the functions of the `PasswordManager` class `static` so as to invoke them without having to instantiate the class. (i.e. `PasswordManager::verifyPassword($password)`).

**Comment by erikgeurts** [comment]
> I think I've made a good progess with steps 1-3.
> 
> I'm still uncertain on what to to with the other users on the system as I don't think there's a good solution that works for everybody. A few random bits:
> 
> * Allow first md5 password check and upgrade the hash upon login. Pros: painless - Cons: bad security!
> * Same as above for a certain period of time. Pros: slightly improved - Cons: still bad security! - Open: how to communicate that
> * Disallow md5. Rely on password recovery alone. Pros: no code needed - Cons: meh user experience - Open: how to communicate that

Good progress!

Looking at the three options you mentioned, I think the first one isn't really a good option, since it would mean that any weak and/or potentially compromised password would simply be ported to the new storage. As you say: bad security.

For option 2 and 3, both have the disadvantage of having to communicate with the user about it, and option 2 is still not very good from a security point of view. So option 2 isn't a good solution either.

So that means option 3 is perhaps not the best from a user experience perspective, but still the best from a security perspective.

Some ideas for how to convey the change to the user:
- as a first step, before even doing the update, a sysadmin should go through the list of usernames, and manually remove each and every user that should no longer have access to the application; this should be done from time to time anyway after all
- during the update process, the existing password for the remaining users should be invalidated, and something should be recorded in the table row for that user that they need to set a new password. One way of approaching this is to simply remove the column that stores the md5 and creating the column that is supposed to store the new hash. Obviously, since the sysadmin needs to be logged in during the update, this is a complication.
- when the user attempts to log in after the update, and he/she has not gone through the procedure yet, show them a message  on screen explaining that a new, safer password concept has been introduced, and prompting them to proceed with a password recovery process. Given that we know the email address associated with that user, a simple click on a button might be sufficient, also mean that we won't have to ask them to recall the email address and we won't have to reveal it on the screen either. One drawback is that this step will not work if the server has not been configured to be able to send out emails.
- if the user performs the password recovery, store their new password in with the new method, and clear the marker that indicates they need to go through password recovery
- obviously, we should urge users to use strong, secure passwords, so a password strength indicator as mentioned in #1292 would be a great addition.

**Comment by mbeccati** [comment]
@twmobius 
> Also at last, I'd suggest making the functions of the PasswordManager class static so as to invoke them without having to instantiate the class. (i.e. PasswordManager::verifyPassword($password)).

I will look into it. The decision to put the PasswordManager in the DI container was to improve testability, but perhaps it's not really needed.

**Comment by mbeccati** [comment]
@erikgeurts 
> as a first step, before even doing the update, a sysadmin should go through the list of usernames, and manually remove each and every user that should no longer have access to the application; this should be done from time to time anyway after all

At best we can suggest that, but we can't really enforce it, especially as this would require checking "User access" of all manager, advertiser and website accounts as well as admins.

> during the update process, the existing password for the remaining users should be invalidated, and something should be recorded in the table row for that user that they need to set a new password. One way of approaching this is to simply remove the column that stores the md5 and creating the column that is supposed to store the new hash. Obviously, since the sysadmin needs to be logged in during the update, this is a complication.

No need to create columns or migrate data etc. If the password field contains 32 characters, it's an md5 hash. New hashes are 60 characters. Since the admin has to type their password during the upgrade, the idea is to somehow re-use is to calculate the new hash, but I haven't fully worked it out already.

> when the user attempts to log in after the update, and he/she has not gone through the procedure yet, show them a message on screen explaining that a new, safer password concept has been introduced, and prompting them to proceed with a password recovery process. 

I'm afraid this is information disclosure, which allows attackers to check if a certain user exists on the system.

**Comment by erikgeurts** [comment]
> Since the admin has to type their password during the upgrade

Is this a new thing? When I do updates, I tend to first log in, so that I can do a password recovery first, if needed. Then I start the update process, meaning I'm already logged in as admin, not needing to type my password.

> I'm afraid this is information disclosure, which allows attackers to check if a certain user exists on the system.

I see, and agree. That does leave the question on how to urge existing users to proceed with the password recovery process so that they can enter a new password (hopefully a secure one) that can then be stored with the new 60 char hash.

**Comment by mbeccati** [comment]
> Is this a new thing? When I do updates, I tend to first log in, so that I can do a password recovery first, if needed. Then I start the update process, meaning I'm already logged in as admin, not needing to type my password.

The oldest thing ever. However, I do remember I made sure the step was optional in case there's already an active admin session. Which for this particular upgrade can't be allowed, as we *definitely* need the password to be typed in if we ever wanted to save a new hash for the admin user.

**Comment by erikgeurts** [comment]
> as we _definitely_ need the password to be typed in if we ever wanted to save a new hash for the admin user.

I see, and understand. However, what would happen if the admin starts the update, and then in mid-air discovers he/she doesn't recall the password?

**Comment by mbeccati** [comment]
That's how it has been working since 20 years, pretty much. Much earlier than password recovery was intorduced. If the admin doesn't recall their password, it's best if they rollback the upgrade.

**Comment by erikgeurts** [comment]
In the release notes / blog post announcing this release, it may be a good idea to specifically recommend that the sysadmin first logs in to the UI, so that they're absolutely certain they have the right password, before proceeding with the actual update.
