### ISSUE TITLE
Problem accessing some pages (urls)

### ISSUE THREAD

**Issue by marieve** [revive-adserver/revive-adserver#1308]
I'm on a fresh new installation (everything is up-to-date).

I can't access thoses pages (accessibles in the top menu):

- /www/admin/advertiser-index.php
- /www/admin/account-index.php
- /www/admin/report-index.php

It redirects me on /www/admin/dashboard.php page.

I have access to /www/admin/dashboard.php and /www/admin/stats.php pages.

I am on a subdomain. I've tried before in a simple subfolder, the problem was that this URL:
/www/admin/advertiser-index.php
was redirected to this URL:
/www/admin/advertiser-

So it gaves me a 404 page. I've created a subdomain to separate Revive AdServer from the main website (in CodeIgniter).

I think there is a problem with the hyphens in the URL. Does anyone encounter this problem before? What can I do for it to work?

Thanks for your help!

Marie-Eve

**Comment by mbeccati** [comment]
Sorry this doesn't look like an issuie in Revive Adserver.

The hyphens behaviour you were seeing seems most likely caused by your webserver and/or CodeIgniter's configuration. It also looks like you do not have administrator or manager privileges when logging in.

That said, I'm afraid that the issues section on our Github pages is not intended for support questions. Please consider posting your question on our community forums at https://forum.revive-adserver.com. If you've already done so, then please just wait patiently for a community member to respond.
