### ISSUE TITLE
Is Revive Adserver impacted by the Log4j vulnerability?

### ISSUE THREAD

**Issue by fritexvz** [revive-adserver/revive-adserver#1337]
Reference link:
[How to test if your Linux server is vulnerable to Log4j](https://www.techrepublic.com/article/how-to-test-if-your-linux-server-is-vulnerable-to-log4j/)

Running command:
`wget https://raw.githubusercontent.com/rubo77/log4j_checker_beta/main/log4j_checker_beta.sh -q -O - | bash`

I got:
`[WARNING] /var/www/web/lib/java-xmlrpc/commons-logging-1.1.jar contains log4j files`

Could someone please check this? Thank you in advance?

**Comment by mbeccati** [comment]
Thanks for your report!

As far as I can tell the file has been introduced along with the example xmlrpc java API client and had been possibly used for some automated tests of the API.

If you followed the security guidelines, the affected jar file is not accessible from outside nor it is used by the application.

We should probably aim to remove the example JAVA client and its support jar files as they are unmaintained and untested since ever.
