### ISSUE TITLE
Error while adding a new banner

### ISSUE THREAD

**Issue by kunzelmanm** [revive-adserver/revive-adserver#1449]
Problem:
Fatal error: Uncaught TypeError: array_merge(): Argument #1 must be of type array, null given in /var/www/lib/max/Dal/DataObjects/Ad_zone_assoc.php:116

Steps To Reproduce:
From a campaign banners page, click add Banner, fill out required fields (I just did upload local banner to adserver), name and image and hit submit. Previously working 5.4.1 upgraded to 5.5.0

Revive 5.5.0
PHP 8.1.13

**Comment by mbeccati** [comment]
I've tried to replicate the issue, but I couldn't. In fact by looking at the code I can't find a way for that argument to be null on a properly working system.

I'd be happy to look deeper into it, but I'm afraid you will need to do some debugging in order to understand how come `$aAdvertiserAccountIds` gets assigned a `null` value.

**Comment by kunzelmanm** [comment]
I figured as much. I doubted that something that was so much a part of the process would not be totally broken.
