### ISSUE TITLE
Banner display limited. but it seems close.gif.

### ISSUE THREAD

**Issue by mydukkan** [revive-adserver/revive-adserver#466]
(Add delivery limitation) Banner display limited. but it seems close.gif.
![revive_bug_screen_3](https://cloud.githubusercontent.com/assets/10612242/5824607/58b89f5c-a0ee-11e4-94c5-3cfb6aa5636f.jpg)

**Comment by marcus-nordreportern** [comment]
I've got the same problem with Interstitial or Floating DHTML-zones since upgrading to 3.1.0.
Despite no active banner for the zone the frame and close-button is viewed.

The invocation code has not changed and the zone is set to stop 

![zz6d57ad18](https://cloud.githubusercontent.com/assets/10628110/5833252/6b7d6bc8-a151-11e4-932b-5298afd3a1d6.png)

**Comment by mbeccati** [comment]
Looks like this might be related to the new blank logging feature. This also seems a feedback that the "interstitials" invocation codes are still used by some of our users.

**Comment by mbeccati** [comment]
@mydukkan @marcus-nordreportern Could you please try this version of al.php?

https://raw.githubusercontent.com/revive-adserver/revive-adserver/51959530134fe261c9d00273dbc26db7fe237f42/www/delivery/al.php

**Comment by mydukkan** [comment]
I tried this, the problem has solved. Thank you.

**Comment by marcus-nordreportern** [comment]
Great, it solved my troubles to. Thanks.

23 jan 2015 kl. 23:23 skrev mydukkan <notifications@github.com>:
