### ISSUE TITLE
NoSQL

### ISSUE THREAD

**Issue by skynet** [revive-adserver/revive-adserver#478]
Any plan for a "Not Only SQL" (NoSQL) - based Revive Adserver?

http://broadstreetads.com/blog/why-openx-is-slow/ - same goes for revive.

**Comment by erikgeurts** [comment]
I don't agree that it is slow. My company run the application at a massive volume with very efficient hardware and software, and the results are pretty amazing.

Most of the times when performance is not up to people's expectations, it turns out that the chosen infrastructure can't possibly deal with the demands of the implementation. That would be a problem for any application.

I would like to suggest this is a topic to discuss on the forums at http://forum.revive-adserver.com/forum/18-performance-scalability-and-reliability/ and not so much a coding issue.

**Comment by skynet** [comment]
:+1:

**Comment by andrewatfornax** [comment]
To answer the original question, though - there are no immediate plans for a NoSQL version, but the plugin framework would support using NoSQL or something else for delivery and logging...

**Comment by skynet** [comment]
Is there any attempt at using a NoSQL DB for logging and delivery? Writing one plugin for myself would  totally offset the benefits of using an "out of box" solution like revive. And it will be interesting to see blog post discussing revive's internals and optimization. Thanks.

**Comment by mbeccati** [comment]
@skynet I think I might have advertised it elsewhere, so... I have written a Redis based delivery logging plugin that can be easily deployed with a large number of delivery boxes. It's not open source though.

**Comment by skynet** [comment]
How would this help me? :)

**Comment by mbeccati** [comment]
Well, anyone having the kind of load that justifies such a need can ask for a quote (until a product page is ready on adserverplugins.com). Plugin licences, custom development and consultancy gigs are what allow me to work for free on the core adserver, after all.

**Comment by skynet** [comment]
if I had a valid business case I would have developed one myself (with my team). Not large traffic here but I don't like the idea that MySQL is constantly under load with Revive.

**Comment by alekseyp** [comment]
Sorry to jump in, but @skynet if your business don't have enough traffic and need to use something else then MySQL then don't waste others people time.

With right hands MySQL alone can handle ten thousands q/s.

More then enough to build a use case and working prototype before you'll need to code something for your exact use case.

**Comment by gamesquat** [comment]
alekseyp +1

**Comment by skynet** [comment]
Sorry to insist but you try to jump to quick into using this project for commercial purposes i.e. selling your services. Other than that please let us have opinions, that's the point of living in the open source world. I also wish you good luck with "revive" as an open source project.

**Comment by mbeccati** [comment]
@skynet In other words you are saying that I should always work for free on the project so that you can make money out of it.

If you think about it, doing consulting gigs, custom plugin development, etc. is in fact what allows me to also spend unpaid time developing the product. Since 2001 I've spent countless hours on this project (both paid and unpaid, to be completely transparent) and I can honestly say that I gave more than a little contribution to the open source world. Where's yours?

**Comment by skynet** [comment]
I tried to help once, (see #154) but revive-adserver is not easy to package and deploy. That's a big barrier for anyone trying to contribute.
