### ISSUE TITLE
Multiple banner campaign bug

### ISSUE THREAD

**Issue by berezuev** [revive-adserver/revive-adserver#485]
I've found a bug, when I using a several banners in 1 campaign, only the first one counts requests correctly.

Here one the screenshot statistics of 6 banners in one campaign. You can see, that that difference between requests and impressions only in the first one (it's wrong).
![default](https://cloud.githubusercontent.com/assets/695546/6570941/76478e3e-c713-11e4-95f8-9b4cc963ecd6.PNG)

**Comment by erikgeurts** [comment]
This is not behavior I've ever seen before. I doubt it is a bug. If it is, it would have surfaced many times in recent years, because this is a very common use case.

I would like to suggest that it is more appropriate to continue discussing this on the community forums at http://forum.revive-adserver.com
