### ISSUE TITLE
banner cache: corrupted html during {clicktag} decoration

### ISSUE THREAD

**Issue by dynamicplus** [revive-adserver/revive-adserver#526]
filename: revive-adserver/www/admin/lib-banner.inc.php
line start: 41 (function phpAds_getBannerCache)

as {clickurl} is prepended to all a href="htt...">and original href is urlencoded
before doing this href must be un-html-escaped (eg: "&amp;" must be "&" and so on...) 
as encoded html chars are lost during re-traslation and re-encoded in wrong way.

the same issue exists on clickTAG flash var.
this var must end ON & also and not only on variable end (single or double quote)

**Comment by mbeccati** [comment]
A quick summary of the bug:

1. HTML requires all `&` to be written as `&amp;`
2. Browsers are smart and can understand plain `&`s anyway, that's why most of the a href links seen in advertising (wrongly) do not use `&amp;`
3. Revive before 3.2.1 couldn't properly parse `<a href="...?a=foo&amp;b=bar">` and the destination redirect was truncated at `?a=foo`
4. 3.2.1 fixes it
