### ISSUE TITLE
"Unknown operator" error in the banner Delivery Options

### ISSUE THREAD

**Issue by martinkrcho** [revive-adserver/revive-adserver#549]
I have upgraded my instance of Revive from 3.0.5 to 3.2.0 yesterday. I am seeing an error message "Unknown operator" when trying to add date restrictions ("Time - Date") to a banner under the "Delivery Options" tab. The dropdown with the operator options only shows first two options the others are blank. This is the HTML code:
```
<select name="acl[0][comparison]" tabindex="2">
  <option value="==">is equal to</option>
  <option value="!=">is different from</option>
  <option value=">"></option><option value=">=">
  </option><option value="<" selected="">
  </option><option value="<="></option>
</select>
```
Is the same happening to somebody else? I tried switching the language to English thinking it's a translations issue, but it's not. Thanks.

**Comment by erikgeurts** [comment]
Thanks for your detailed report.

I can confirm that I'm seeing this too in a recently upgraded v3.2.0 installation:
![image](https://cloud.githubusercontent.com/assets/5102461/7586617/e9a51cd0-f8ae-11e4-9631-c90a800f74c0.png)

This is most likely caused by the language file cleanup that was performed recently, it appears that some of the original English texts have been removed inadvertently.

**Comment by roybaum** [comment]
I, too, have seen this exact same error. I've tried installing 3.2.0 three times to two different hosts with the same result.

**Comment by steveganz** [comment]
Here are the missing strings from /lib/max/language/en/default.lang.php:

		$GLOBALS['strLaterThan']                  = "is later than";
		$GLOBALS['strLaterThanOrEqual']           = "is later than or equal to";
		$GLOBALS['strEarlierThan']                = "is earlier than";
		$GLOBALS['strEarlierThanOrEqual']         = "is earlier than or equal to";
		$GLOBALS['strNotContains']                = "doesn't contain";
