### ISSUE TITLE
Javascript invocation code no longer presented on v3.2.x

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#558]
After upgrading to v3.2.x I noticed that the Invocation Code screen no longer offers to generate the traditional Javascript invocation code:
![image](https://cloud.githubusercontent.com/assets/5102461/7678031/3a6861d0-fd51-11e4-903a-672504b46cf8.png)

The settings screen of the Invocation Tags Plugin (v1.4.3) doesn't offer separate check boxes for traditional javascript and async either:
![image](https://cloud.githubusercontent.com/assets/5102461/7678003/0ff79e70-fd51-11e4-9b11-617812678235.png)

**Comment by jenbrannstrom** [comment]
We are currently experiencing a problem that seems to be either the same or at least closely related.
I am new to revive so I can't say for certain.
(Our install is using Revive Adserver v3.1.0 running on nginx 1.4.6, PHP 5.3.3 and MySQL 5.1.73-log.)

The issue is: the drop-down has no invocation tag at all
http://prntscr.com/77nu6b

**Comment by erikgeurts** [comment]
If you're indeed using v3.1.0 then this is not a related issue, because this issue is specifically about v3.2.0.

Please consider posting your support question on our community forums at http://forum.revive-adserver.com.

**Comment by jenbrannstrom** [comment]
posted
http://forum.revive-adserver.com/topic/1717-no-invocation-tag-appears/
