### ISSUE TITLE
IAB VAST Plugin 1.11.1 -  revive 3.2.0 bug

### ISSUE THREAD

**Issue by sime2408** [revive-adserver/revive-adserver#573]
Hi, I am using revive v3.2.0 and PHP 5.3.3

I have an error (in pear lib I guess) while saving Video ads. I can't save them. The message that I recive is this :

PHP Fatal error:  Call to undefined method stdClass::insert() in /revive-adserver-3.2.0/plugins/bannerTypeHtml/vastInlineBannerTypeHtml/commonAdmin.php on line 147, referer: http://mysite/www/admin/banner-edit.php?clientid=xx&campaignid=xxxx

This error is normally thrown when a class instance has been serialised to disk, then re-read/deserialised in another request but the class definition has not been loaded yet, so PHP creates it as an "stdClass" (standard class.)

So far for $doBanners I am getting false... seems that : $doBanners = OA_Dal::factoryDO('banner_vast_element'); on line 113 is problematic due to factoryDO returning false.  This chrashes when I want to save inline video ad. 

Please help it's urgent, should I reinstall IAB VAST Plugin? In that case I will lost all my video ads :(
P.S. I upgraded from openx-2.8.11 to revive-3.0.6 and then to revive-3.2.0

**Comment by sime2408** [comment]
I re-installed plugin and everything seems to be working fine. But I lost all my statistics and data

**Comment by mbeccati** [comment]
The error was due to the fact that the plugin table `ox_banner_vast_element` was not there in the first place, I'm afraid. 

to be honest I have no idea how that could happen as Revive itself deletes the tables only when uninstalling a plugin.

For now, I'm closing the issue and I'm marking the issue as invalid. Unless you can prove that Revive mistakenly deleted the table and you have a way to replicate the issue, of course.

**Comment by sime2408** [comment]
Thank you for your response. Yes, I uninstalled first, I haven't thought that I can just Import code only from earlier version of plugin and than import back version 1.11.1. Doing that way i wouldn't lost my data. Eh, anyway it works now. Sorry for false flag.
