### ISSUE TITLE
_ga query parameter error.

### ISSUE THREAD

**Issue by danbyrd** [revive-adserver/revive-adserver#574]
when I click my banners google analytics is adding multiple _ga query parameters that are out of order.

The banner appears on http://www.livestrong.org/events/

The target URL I added on the revive cms was:
http://www.livestrong.org/events/1920/

However when I click the banner on the site it directs me to this URL:
http://www.livestrong.org/events/1920/&_ga=1.93247005.1636281231.1433443493?_ga=1.93247005.1636281231.1433443493

The out of order parameter is causing my page target link to error out.

Have you experienced this issue before? Do you have any other solutions other than turning off cross domain tracking in Google Analytics?

**Comment by erikgeurts** [comment]
Revive Adserver does not add anything of that nature to the destination URL of a banner. Are you sure this is caused by the ad server?

**Comment by danbyrd** [comment]
It is most definitely NOT caused by the ad server. Google Analytics adds the parameter for cross domain user tracking. I was just wondering if you had encountered this before and if there were any solutions other than turning the feature off in Google Analytics would would compromise our site data.

**Comment by erikgeurts** [comment]
If this is not caused by an ad server, and not even ours, then I don't see the purpose of opening an issue here. You could consider posting a question on our forums at http://forum.revive-adserver.com/forum/24-off-topic/

**Comment by sorinpopescu** [comment]
Hi.
I can confirm the issue. Is there any way to fix this?
Thanks

**Comment by sorinpopescu** [comment]
Hi.
Let me add the details why this is an Revive issue.
I have attached a file.
Please look close how the url to be clicked it's formated:

delivery / ck.php ? params ... & _oadest = domain.tld/folder & _ga = 

As you can see Google add corectly the _ga - because there is already an "?" in the url.
When it goes to Revive for tracking and gets redirected, the last part is not well rewrited - so the first sign should be "?" instead of "&" - there should be a check for those signs.
We "skiped" this issue by adding the "?" to all our urls in Revive - but it's not a strong solution.
Can this be fixed or patched?
Thanks

![revive-issue](https://cloud.githubusercontent.com/assets/2951110/13599880/1cebc5c8-e52e-11e5-9fb2-7f8c28cb6d8a.png)

**Comment by mbeccati** [comment]
GA messes with the URLs, so it would be their duty to detect Revive click URLs and fix. Revive can't know if the destination URL has been fiddled with

**Comment by moe2k** [comment]
I would like to disagree @mbeccati @erikgeurts 

Let's say we're displaying a banner on a website https://example.com.

Take the following banner url:
`https://lp.example.com/landingpage.html`

When the banner is rendered, it's link points to this revive tracking url:
`https://ads.example.com/ox/www/delivery/ck.php?oaparams=2__bannerid=91__zoneid=9__cb=2ab5bb9ab6__oadest=https%3A%2F%2Flp.example.com%2Flandingpage.html`

So far so good. 

Our Google analytics has cross domain tracking enabled and is configured to track links to ads.example.com because it's a subdomain of example.com. Now Google Analytics' autoLinker plugin is also enabled and fiddles with the URL onclick like this:

`https://ads.example.com/ox/www/delivery/ck.php?oaparams=2__bannerid=91__zoneid=9__cb=2ab5bb9ab6__oadest=https%3A%2F%2Flp.example.com%2Flandingpage.html&2.13246578.1324567891.2345678912-132456789.132465789`

Note the `&` delimiter - which is technically correct because _ga is the second parameter in this URL. Of course analytics does not recognize that the actual target is a urlencoded part of "oaparams" after "oadest=".  But technically, we're still good so far.

Now revive redirects to this URL:

`https://lp.example.com/landingpage.html&_ga=2.13246578.1324567891.2345678912-132456789.132465789?_ga=2.13246578.1324567891.2345678912-132456789.132465789`

Now we have a problem, because the parameter is doubled for some strange reason and in the wrong order (delimiter wise). Note the & before the first _ga and the ? before the second _ga. 

Maybe that is because any params added to the tracking URL are passed-through, and at the same time they are interpreted as part of the oadest-parameter for compatibility reasons? Or maybe some double rewriting happens accidentally? Just speculating here.

So one might argue that tracking URLs should not be fiddled with. But if they are (and we can't always prevent it), revive technically should behave in a non-breaking way.

**Comment by mbeccati** [comment]
@moe2k if you insist on having your Revive URLs mangled (which IMHO you shouldn't), then just add a parameter to your destination URLs, e.g. `https://lp.example.com/landingpage.html?a=1`.

**Comment by moe2k** [comment]
Good Idea. This could at least be a useful workaround, however I still think that the root cause should be fixed.
