### ISSUE TITLE
Banner Delivery Cache Store Type - Redis

### ISSUE THREAD

**Issue by skynet** [revive-adserver/revive-adserver#586]
Is it possible to implement this? Redis' superiority is evident in almost every aspect of cache management.

**Comment by mbeccati** [comment]
https://github.com/adserverplugins/apDeliveryCacheRedis/releases

**Comment by skynet** [comment]
Excellent, thank you.

**Comment by erikgeurts** [comment]
I would like to mention that in addition to a plugin that enables caching using Redis, we have also developed a plugin that performs statistics collection in Redis. Instead of the usual bucket tables in Revive Adserver, all requests, impressions, clicks, conversions and video tracking events are collected in memory, and written to the database at the end of the hour for further processing.

We've implemented this in a number of installations and have seen dramatic performance improvements. At the time of this writing, there is no product page for this plugin yet. For more information, please contact us via http://www.adserverplugins.com/contact/

Full disclosure: the Redis Logging plugin is a paid product offered by a third party owned by @erikgeurts and @mbeccati . The proceeds from selling licenses of this and comparable software products enable us to spend unpaid time on the open source project.

**Comment by skynet** [comment]
Understand the need to support the work that you're doing on Revive and its plugins, but how about an open source version of this Redis-based Statistics plugin, with paid support?

**Comment by erikgeurts** [comment]
When you purchase a license of the Redis Logging plugin, you basically provide us with part of our income that enables us to spend unpaid time on the open source project.

You would benefit in two ways: you'd have an enterprise grade plugin plus the support that comes with it, and the open source project on which all of this is based also benefits. That's good for you and for the rest of the community.

**Comment by skynet** [comment]
:+1:
