### ISSUE TITLE
xml-rpc examples for Revive Adserver

### ISSUE THREAD

**Issue by ccdaisy** [revive-adserver/revive-adserver#704]
Hi guys, Im about to deploy an adserver in our system. As I knew from your documentation, we can use xml-rpc to ask for ads. But there is no example for it. There are only async js/js tag/iframe tag/local mode tag. Could you pls let me know the xml-rpc protocol for Revive Adserver?

many thanks.

**Comment by ccdaisy** [comment]
I tried the xmlrpc in http://115.29.35.47/adserver/www/api/v2/xmlrpc/. And I tried the java code for testing. All passed. But where is the rpc service for get advertisement to show? Still waiting for an answer.
We do mobile apps, so we need to use rpc to show native ads. Many thanks.

**Comment by erikgeurts** [comment]
You will first need to enable "Allow XML-RPC Invocation Tag" in the Invocation Tags plugin settings, i.e. `.../plugin-settings.php?group=oxInvocationTags&parent=openXInvocationTags`.

That will add XML-RPC invocation to the dropdown and show an example.

However, I think the best place to have this topic is at http://forum.revive-adserver.com/forum/19-for-developers/ . We aim to use Github issues purely for bugs and development.

**Comment by primewang** [comment]
@erikgeurts  tried the xmlrpc in http://localhost:8080/lib/xmlrpc/php/tests/integration/Banner.api.test.php
but show 
PHP Notice:  Use of undefined constant MAX_PATH - assumed 'MAX_PATH' in /data2/wwwroot/revive_adserver/lib/xmlrpc/php/tests/integration/Banner.api.test.php on line 13

how can i do it

**Comment by primewang** [comment]
openXInvocationTags is enable in my system

**Comment by mbeccati** [comment]
I'm not sure what you're trying to do. The file belongs to the integration testing suite and is not for public usage.

**Comment by YPCrumble** [comment]
@mbeccati I posted a related ticket per @erikgeurts suggestion here: https://forum.revive-adserver.com/topic/4909-documenting-the-xmlrpc-api-and-endpoints/

I'd love to help contribute to the documentation for instructions and examples for using the API. I'd also be interested in building a Python wrapper for the API and/or a REST implementation using Django Rest Framework, if that's desirable. The only issue is I would need to ask a few questions to understand how to get started because it's currently undocumented :). Thanks for any feedback / suggestions!

**Comment by erikgeurts** [comment]
This is a closed Github issue from about 18 months ago.

You appear to be mixing up the API for ad management and statistics (which can be called over xml-rpc) and the xml-rpc zone invocation code. These two have no relation to each other.

**Comment by YPCrumble** [comment]
@erikgeurts the tone of your response is unusual for an open source repo - it's very rare for me to offer help and get a dismissive response. I then took a deeper look into why you wouldn't be interested in my help and realized you are the author of the [Revive Adserver REST API](https://www.reviveadserverrestapi.com/). Is that why my suggestion isn't something you seem interested in? I'd prefer not to waste any of either of our time if that's the case. I apologize in advance if I'm mistaken.

**Comment by erikgeurts** [comment]
I'm sorry you took it like that, I never intended that. If I had wanted to promote that product you linked to (thanks for that :) ) I could have done that, but obviously I didn't because here on github it's just about the open source project.

By the way, there's no shame in offering commercial products or services around an open source project, the revenue from that enables me to voluntarily contribute a substantial amount of time *every week* to this project.

Nevertheless, I still think you are confusing the API (which is built into Revive Adserver and is free of charge) that can be accessed via XML-RPC, and the zone invocation code using XML-RPC. These two have no relationship with each other in any way.

This Github issue is about zone invocation code, you started adding comments about the API. You're welcome to offer help, and I don't think I ever said (or even replied) that I was dismissing that.

**Comment by YPCrumble** [comment]
@erikgeurts thanks for your thoughtful response! I completely agree no shame in offering the premium product. I also apologize for confusing the API's. I suppose my only excuse is that it's difficult to identify what is what because the documentation is a little limited.

I have a couple thoughts on the API and will send you a note through your contact form on the website on your profile.
