### ISSUE TITLE
https on /admin/updates-product.php not good.

### ISSUE THREAD

**Issue by master3395** [revive-adserver/revive-adserver#737]
If i use force https and then go to /admin/updates-product.php
It will keep refreshing the page, in a loop, it will never stop.

**Comment by erikgeurts** [comment]
I am unable to reproduce this behavior. Are you sure this is not some sort of rewrite rule on your server?

As indicated in the instructions while opening a new issue, I recommend you take this to our community forums at http://forum.revive-adserver.com first. If it turns out to be a bug, we can continue here.

**Comment by andrewatfornax** [comment]
No feedback here, closing. Please re-open if support via forums suggests this is a bug. Thanks!
