### ISSUE TITLE
Banner delivery options "XX AND (YY OR ZZ)"

### ISSUE THREAD

**Issue by 2ge** [revive-adserver/revive-adserver#774]
it would be really great if this is supported. I know, workaround is using REGEXP, but also in many cases this is not enough. Please consider 

Thank you for great software

**Comment by andrewatfornax** [comment]
Can this be done using channels? That is, put the OR grouped items into a channel, and then AND the channel with the other item?

**Comment by andrewatfornax** [comment]
Yes, this does work. I have tested the evaluation order of delivery limitations re: targeting channels, and this is how things work. I have created new documentation that explains this (as well as new documentation on targeting channels in general, and an update to the delivery limitations re: using targeting channels, now that we have documentation on this).

The main area of interest re: this issue is: https://documentation.revive-adserver.com/display/DOCS/Delivery+Limitation+Evaluation+Order
