### ISSUE TITLE
Campaign name is empty at Statistics Report breadcrumb

### ISSUE THREAD

**Issue by iqueiroz** [revive-adserver/revive-adserver#810]
Problem:
When accessing the report "Distribution history (Campaign)" and filtering by a website and campaign the field 'Campaign' on the breadcrumb stays empty.
The same occurs when you select a specific date and the view changes to 'Daily statistics'.
Screenshots are attached.

Steps To Reproduce:
1. Click on 'Statistics' on the header menu
2. Click on 'Websites & Zones' on the sidebar
3. Click on a Website on the list which contains data
4. Click on 'Campaign Distribution'
5. Select any Campaign on the list which contains data
6. 🐞 Issue: Note that the Campaign name is empty on the breadcrumb (screenshot attached)
7. Go ahead and select a date which contains data.
8. 🐞 Issue: Note that the Campaign name remains empty on the breadcrumb (screenshot attached).

Environment:
Revive most recent version: 4.0.1 ✔️ 

Apache 2.4:
> Package: apache2
> Status: install ok installed
> Priority: optional
> Section: httpd
> Installed-Size: 463
> Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
> Architecture: amd64
> Version: 2.4.7-1ubuntu4.13
> Replaces: apache2.2-common
> Depends: lsb-base, procps, perl, mime-support, apache2-bin (= 2.4.7-1ubuntu4.13), apache2-data (= 2.4.7-1ubuntu4.13)

PHP 7.0:
> Package: php7.0
> Status: install ok installed
> Priority: optional
> Section: php
> Installed-Size: 91
> Maintainer: Debian PHP Maintainers <pkg-php-maint@lists.alioth.debian.org>
> Architecture: all
> Version: 7.0.15-1+deb.sury.org~trusty+1
> Provides: php
> Depends: libapache2-mod-php7.0 | php7.0-fpm | php7.0-cgi, php7.0-common

Screenshots:
![distribution history campaign](https://cloud.githubusercontent.com/assets/1731058/22594301/48b9e224-ea01-11e6-830e-9ad3bb7886b6.png)
![daily statistics](https://cloud.githubusercontent.com/assets/1731058/22594304/4a8ef940-ea01-11e6-934b-4f110853c420.png)

**Comment by andrewatfornax** [comment]
Looks like the code that is checking if the logged in user has permissions to see the campaign details is not working - and as a result, it's excluding the user from seeing the campaign name.

Tracking down why this is happening.

**Comment by andrewatfornax** [comment]
This appears to have resolved the issue with the exception of the top-level Advertiser distribution history by Zone. 

This appears to be an error that is causing only one zone ID to be returned, even though the raw query that is generated is finding multiple rows, with all relevant zone IDs in the result.

Need to understand why the multiple zones are not making it through, so that the intersection process will allow the relevant zones to be used, so that the zone details will appear on this page.

Note: Check that the same issue (once understood) does not affect any of the other cross-history functions.

**Comment by andrewatfornax** [comment]
I think I have tracked down the problem, but I need to get the test framework working in my new development environment before I can commit a change, because it's at the very bottom of an old data access layer, so I'm concerned that my changes will break things, and want to be able to execute the tests before going ahead.

**Comment by iqueiroz** [comment]
Thanks!
