### ISSUE TITLE
Allow multiple banners on email zone

### ISSUE THREAD

**Issue by thesios** [revive-adserver/revive-adserver#832]
This is a request for investigation into allowing multiple banners into email zones

Andrew requested I create Issue for this.

I will like to be able to serve multiple banners on an email zone

**Comment by mbeccati** [comment]
Yeah, the problem is that it's technically not possible, unless they have different delivery times. At any point in time there needs to be a 1:1 link between what is served and what its click url is, as cookies aren't supported.

**Comment by andrewatfornax** [comment]
Thanks for the ticket @thesios! I did indeed ask that you create this, as I thought it sounded like a good idea (or that we at least have a different type of zone that allowed it).

However, I had a chat with @mbeccati tonight about the technical reasons as to why it can't be done, and now that I understand the reasons, I've added a KB article about this:

https://documentation.revive-adserver.com/pages/viewpage.action?pageId=9044101

Hopefully, that makes it clear why @mbeccati is saying we can't do this - because we can't determine the click URL to use if there are multiple active banners - at least, not without using cookies or JavaScript (which can't be guaranteed to work in an email client).

Hopefully that makes sense?
