### ISSUE TITLE
Installation on google app engine

### ISSUE THREAD

**Issue by scriptburn** [revive-adserver/revive-adserver#978]
Hi,

Is it possible to install it on app engine? where it has read only filesystem

**Comment by mbeccati** [comment]
As clearly indicated during the process of opening an issue here, it is recommended to post this type of question on our community forums at [https://forum.revive-adserver.com](https://forum.revive-adserver.com). If it turns out that there is a bug or some other issue that developers need to look at, we will gladly re-open it here.

**TL;DR** Nope, sorry.
